galaxy_info:
  author: fabien arcellier
  description: instanciate a mongodb that listens on 0.0.0.0:27017

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
      - precise
      - trusty
      - xenial

  galaxy_tags: []

dependencies: []
