---
- hosts: all
  sudo: no
  vars:
  tasks:

  - name: Ubuntu | Ensure installation is up to date
    apt: upgrade=safe

  - name: Mongodb | Ensure unofficial repository apt key is present
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

  - name: Mongodb | Ensure repository is present
    apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present
    register: aptrepository_mongodb

  - name: Ubuntu | Ensure apt listing is up to date
    apt: update_cache=yes
    when: aptrepository_mongodb.changed

  - name: Mongodb | Ensure database is installed
    apt: name=mongodb-org

  - name: Mongodb | Ensure mongodb is listen traffic from a specific network interface
    lineinfile: >
      dest=/etc/mongod.conf
      "regexp=^(.*)bindIp: .*$"
      "line=\1bindIp: {{ mongodb_bindip }}"
      backrefs=yes
      state=present
    notify: Mongodb | Ensure service is reloaded

  - name: Mongodb | Ensure service is started
    service: name=mongod state=started

  roles:

  handlers:
  - name: Mongodb | Ensure service is reloaded
    service: name=mongod state=reloaded
