---
- name: ensure mongodb unofficial repository apt key is present
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927

- name: ensure mongodb repository is present
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes

- name: ensure mongodb is installed
  apt:
    name: mongodb-org

- name: ensure mongodb is listen traffic from all network interface
  lineinfile:
    backrefs: yes
    dest: /etc/mongod.conf
    regexp: "^(.*)bindIp: .*$"
    line: '\1bindIp: {{ mongodb_bindip }}'
    state: present
  notify: ensure mongodb service is reloaded

- name: ensure mongodb service is deployed
  copy:
    src: mongod.service
    dest: /etc/systemd/system/mongod.service
    owner: root
    group: root
    mode: 0644

- name: ensure json file is copied to vm
  copy:
    src: cities15000.json
    dest: /tmp/cities15000.json

- name: ensure mongodb service is started
  service: name=mongod state=started

- name: wait MongoDB port is listening
  wait_for: 
    host: "{{ mongodb_bindip }}"
    port: "{{ mongodb_net_port }}" 
    delay: "5" 
    state: "started"

- name: import Dataset
  shell: mongoimport --db geography --collection cities --file /tmp/cities15000.json --jsonArray
